---
kind: pipeline
name: dart-dev

steps:
- name: environment
  image: dart:beta
  pull: always
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart --version

- name: dependencies
  image: dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart pub get

- name: format
  image: dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart format -o none --set-exit-if-changed .

- name: lint
  image: dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart analyze lib
  - dart analyze test

- name: test
  image: dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart test --coverage coverage

- name: generate-lcov
  image: dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - dart pub global activate coverage
  - dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage

- name: upload-coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
    - coverage/lcov.info

volumes:
- name: cache
  temp: {}

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
