---
kind: pipeline
name: dart-dev

steps:
- name: environment
  image: google/dart:beta
  pull: always
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart --version

- name: dependencies
  image: google/dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart pub get

- name: format
  image: google/dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  # Using `dartfmt` is deprecated but this step using `dart format` does not set exit code
  - dartfmt --set-exit-if-changed .

- name: lint
  image: google/dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart analyze lib
  - dart analyze test

- name: test
  image: google/dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  # Using `pub run test` is deprecated but this step using `dart run test` does not complete
  - pub run test --coverage coverage

- name: generate-lcov
  image: google/dart:beta
  volumes:
  - name: cache
    path: /root/.pub-cache
  commands:
  - dart pub global activate coverage
  - format_coverage --verbose --lcov --packages .packages --base-directory . --report-on lib --report-on test --in coverage --out coverage/lcov.cov

- name: upload-coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
    - coverage/lcov.cov

volumes:
- name: cache
  temp: {}

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
